[package]
name = "image-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
nn = "0.1.6"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
configparser = "3.0.2"
